### ISSUE TITLE
Crash on Startup 1.1.0 Release: Minecraft 1.12.2 net.minecraftforge.fml.common.LoaderExceptionModCrash: Caught exception from Engineer's Decor (engineersdecor) 

### ISSUE THREAD

**Issue by erebus42** [stfwi/engineers-decor#102]
Time: 6/28/20 11:11 PM
Description: There was a severe problem during mod loading that has caused the game to fail

net.minecraftforge.fml.common.LoaderExceptionModCrash: Caught exception from Engineer's Decor (engineersdecor)
Caused by: java.lang.VerifyError: Bad local variable type
Exception Details:
  Location:
    wile/engineersdecor/blocks/BlockDecorFurnace$BTileEntity.func_73660_a()V @438: aload_3
  Reason:
    Type integer (current frame, locals[3]) is not assignable to reference type
  Current Frame:
    bci: @438
    flags: { }
    locals: { 'wile/engineersdecor/blocks/BlockDecorFurnace$BTileEntity', 'net/minecraft/block/state/IBlockState', integer, integer, 'net/minecraft/item/ItemStack', 'net/minecraft/item/ItemStack', integer, 'net/minecraft/item/Item' }
    stack: { 'net/minecraft/item/ItemStack', integer, 'wile/engineersdecor/blocks/BlockDecorFurnace$BTileEntity' }
  Bytecode:
    0x0000000: 2a59 b400 c304 645a b500 c39e 0004 b12a
    0x0000010: 07b5 00c3 2ab4 0174 2ab4 0177 b602 2c4c
    0x0000020: 2bb9 00f5 0100 c100 0d9a 0004 b12a b602
    0x0000030: 2e3d 1c99 000d 2a59 b400 bd07 64b5 00bd
    0x0000040: 2ab4 00bf 9c00 152a 2ab4 00b7 04b6 0140
    0x0000050: c000 8eb8 0230 b500 bf2a b400 bd9c 0008
    0x0000060: 2a03 b500 bd2a b401 74b4 0233 9900 04b1
    0x0000070: 033e 2a59 b400 c104 645a b500 c19d 008d
    0x0000080: 2a08 b500 c12a 1007 1008 04b7 0235 9900
    0x0000090: 0504 3e2a 0510 0704 b702 3599 0005 043e
    0x00000a0: 2a08 0404 b702 3599 0005 043e 2a10 0608
    0x00000b0: 04b7 0235 9900 0504 3e2a 0603 04b7 0235
    0x00000c0: 9900 0504 3e2a 0706 04b7 0235 9900 0504
    0x00000d0: 3e2a b202 3ac6 002d 2ab4 00b7 1009 b601
    0x00000e0: 40c0 008e b601 a5b2 023a a500 182a b400
    0x00000f0: b710 0ab6 0140 c000 8eb6 01a5 b202 3aa6
    0x0000100: 0007 04a7 0004 03b5 008c 2ab4 00b7 04b6
    0x0000110: 0140 c000 8e3a 042a b400 933a 052a 2ab4
    0x0000120: 00b7 03b6 0140 c000 8eb5 0093 2ab6 022e
    0x0000130: 9a00 1519 04b6 0137 9a01 0d2a b400 93b6
    0x0000140: 0137 9a01 032a b400 9319 05b6 0153 9a00
    0x0000150: 142a 03b5 00b9 2a2a 2ab4 0093 b601 69b5
    0x0000160: 00bb 2ab6 01e3 3606 1506 9900 6b2a b400
    0x0000170: bd9d 0064 2ab2 005f 1904 b802 3087 6b0e
    0x0000180: 1402 3bb8 023f 8eb5 00bd 2a2a b400 bdb2
    0x0000190: 005d 6811 00c8 6cb5 00bf 2ab6 022e 9900
    0x00001a0: 3704 3e19 04b6 0137 9a00 2d19 04b6 01a5
    0x00001b0: 3a07 1904 042a 2db8 0245 b601 cc19 04b6
    0x00001c0: 0137 9900 132a b400 b704 1907 1904 b602
    0x00001d0: 4ab6 015b 572a b400 bd9e 0057 1506 9900
    0x00001e0: 522a 59b4 00b9 0760 b500 b92a b400 8c99
    0x00001f0: 001c 2ab4 0208 b200 61a1 0012 2a03 b502
    0x0000200: 082a 59b4 00b9 0760 b500 b92a b400 b92a
    0x0000210: b400 bba1 002f 2a03 b500 b92a 2a2a b400
    0x0000220: 93b6 0169 b500 bb2a b602 4c04 3ea7 0015
    0x0000230: 2a2a b400 b905 6403 2ab4 00bb b800 59b5
    0x0000240: 00b9 a700 232a b602 2e9a 001c 2ab4 00b9
    0x0000250: 9e00 152a 2ab4 00b9 0564 032a b400 bbb8
    0x0000260: 0059 b500 b91c 2ab6 022e 9f00 2104 3e2a
    0x0000270: b401 742a b401 772b b202 502a b602 2eb8
    0x0000280: 0256 b902 5a03 00b6 025e 571d 9900 072a
    0x0000290: b601 6cb1                              
  Stackmap Table:
    same_frame(@15)
    append_frame(@45,Object[#241])
    append_frame(@64,Integer)
    same_frame(@89)
    same_frame(@101)
    same_frame(@112)
    append_frame(@147,Integer)
    same_frame(@160)
    same_frame(@172)
    same_frame(@185)
    same_frame(@197)
    same_frame(@209)
    same_locals_1_stack_item_frame(@258,Object[#2])
    same_locals_1_stack_item_frame(@262,Object[#2])
    full_frame(@263,{Object[#2],Object[#241],Integer,Integer},{Object[#2],Integer})
    same_frame(@266)
    append_frame(@325,Object[#142],Object[#142])
    same_frame(@354)
    append_frame(@469,Integer)
    same_frame(@523)
    same_frame(@560)
    same_frame(@578)
    chop_frame(@581,1)
    same_frame(@613)
    same_frame(@651)
    same_frame(@659)

	at wile.engineersdecor.detail.ModConfig.apply(ModConfig.java:615)
	at wile.engineersdecor.detail.ModConfig.onPostInit(ModConfig.java:485)
	at wile.engineersdecor.ModEngineersDecor.postInit(ModEngineersDecor.java:114)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at net.minecraftforge.fml.common.FMLModContainer.handleModStateEvent(FMLModContainer.java:637)
	at sun.reflect.GeneratedMethodAccessor3.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at com.google.common.eventbus.Subscriber.invokeSubscriberMethod(Subscriber.java:91)
	at com.google.common.eventbus.Subscriber$SynchronizedSubscriber.invokeSubscriberMethod(Subscriber.java:150)
	at com.google.common.eventbus.Subscriber$1.run(Subscriber.java:76)
	at com.google.common.util.concurrent.MoreExecutors$DirectExecutor.execute(MoreExecutors.java:399)
	at com.google.common.eventbus.Subscriber.dispatchEvent(Subscriber.java:71)
	at com.google.common.eventbus.Dispatcher$PerThreadQueuedDispatcher.dispatch(Dispatcher.java:116)
	at com.google.common.eventbus.EventBus.post(EventBus.java:217)
	at net.minecraftforge.fml.common.LoadController.sendEventToModContainer(LoadController.java:219)
	at net.minecraftforge.fml.common.LoadController.propogateStateMessage(LoadController.java:197)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at com.google.common.eventbus.Subscriber.invokeSubscriberMethod(Subscriber.java:91)
	at com.google.common.eventbus.Subscriber$SynchronizedSubscriber.invokeSubscriberMethod(Subscriber.java:150)
	at com.google.common.eventbus.Subscriber$1.run(Subscriber.java:76)
	at com.google.common.util.concurrent.MoreExecutors$DirectExecutor.execute(MoreExecutors.java:399)
	at com.google.common.eventbus.Subscriber.dispatchEvent(Subscriber.java:71)
	at com.google.common.eventbus.Dispatcher$PerThreadQueuedDispatcher.dispatch(Dispatcher.java:116)
	at com.google.common.eventbus.EventBus.post(EventBus.java:217)
	at net.minecraftforge.fml.common.LoadController.distributeStateMessage(LoadController.java:136)
	at net.minecraftforge.fml.common.Loader.initializeMods(Loader.java:754)
	at net.minecraftforge.fml.client.FMLClientHandler.finishMinecraftLoading(FMLClientHandler.java:336)
	at net.minecraft.client.Minecraft.func_71384_a(Minecraft.java:535)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:378)
	at net.minecraft.client.main.Main.main(SourceFile:123)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)

**Comment by stfwi** [comment]
Hi, hmm, that's a thing I did not see before ;). Can you provide some additional data, like the versions of Forge, or if that problem is reproducible? It's hard to find the problem otherwise. Cheers, -

**Comment by erebus42** [comment]
You could probably close this. I tried again in a lighter mod pack and wasn't able to reproduce it. If I see it again, I'll re-open.

**Comment by stfwi** [comment]
Oky, thanks for the quick feedback.

**Comment by madmax3004** [comment]
@erebus42 

Could you post your crash log please? I'm getting the same crash and would like to compare mod lists.

**Comment by erebus42** [comment]
[crash-2020-06-28_23.27.41-client.txt](https://github.com/stfwi/engineers-decor/files/4853049/crash-2020-06-28_23.27.41-client.txt)
