### ISSUE TITLE
1.1.22-b1: Incompatibility with Radium 0.7.10

### ISSUE THREAD

**Issue by mattfg** [stfwi/engineers-decor#219]
Not sure what all information to give you but here's the crash report. After this I removed engineer's decor the game and the game launched correctly. I put it back and removed Radium and it also launched correctly.

```
---- Minecraft Crash Report ----
// Don't do that.

Time: 7/15/22, 5:01 PM
Description: Rendering overlay

java.lang.NullPointerException: Cannot invoke "net.minecraft.world.level.block.Block.m_49966_()" because the return value of "wile.engineersdecor.libmc.detail.Registries.getBlock(String)" is null
	at wile.engineersdecor.ModContent.lambda$initBlocks$2(ModContent.java:93) ~[engineersdecor-1.18.2-1.1.22-b1.jar%2379!/:1.1.22-b1] {re:classloading}
	at net.minecraft.world.level.block.StairBlock.getModelState(StairBlock.java:282) ~[client-1.18.2-20220404.173914-srg.jar%23128!/:?] {re:classloading,pl:accesstransformer:B,xf:fml:forge:stairsblock}
	at net.minecraft.world.level.block.StairBlock.getModelBlock(StairBlock.java:279) ~[client-1.18.2-20220404.173914-srg.jar%23128!/:?] {re:classloading,pl:accesstransformer:B,xf:fml:forge:stairsblock}
	at net.minecraft.world.level.block.StairBlock.m_6724_(StairBlock.java:147) ~[client-1.18.2-20220404.173914-srg.jar%23128!/:?] {re:classloading,pl:accesstransformer:B,xf:fml:forge:stairsblock}
	at net.minecraft.world.level.block.state.BlockBehaviour$BlockStateBase.handler$zpo001$init(BlockBehaviour.java:2400) ~[client-1.18.2-20220404.173914-srg.jar%23128!/:?] {re:mixin,re:computing_frames,re:classloading,pl:mixin:APP:immersiveengineering.mixins.json:coremods.AbstractBlockStateMixin,pl:mixin:APP:apoli.mixins.json:AbstractBlockStateMixin,pl:mixin:APP:radium.mixins.json:ai.pathing.AbstractBlockStateMixin,pl:mixin:APP:radium.mixins.json:block.flatten_states.AbstractBlockStateMixin,pl:mixin:APP:radium.mixins.json:chunk.block_counting.AbstractBlockStateMixin,pl:mixin:APP:valhelsia_core.mixins.json:BlockStateBaseMixin,pl:mixin:A}
	at net.minecraft.world.level.block.state.BlockBehaviour$BlockStateBase.m_60611_(BlockBehaviour.java) ~[client-1.18.2-20220404.173914-srg.jar%23128!/:?] {re:mixin,re:computing_frames,re:classloading,pl:mixin:APP:immersiveengineering.mixins.json:coremods.AbstractBlockStateMixin,pl:mixin:APP:apoli.mixins.json:AbstractBlockStateMixin,pl:mixin:APP:radium.mixins.json:ai.pathing.AbstractBlockStateMixin,pl:mixin:APP:radium.mixins.json:block.flatten_states.AbstractBlockStateMixin,pl:mixin:APP:radium.mixins.json:chunk.block_counting.AbstractBlockStateMixin,pl:mixin:APP:valhelsia_core.mixins.json:BlockStateBaseMixin,pl:mixin:A}
	at net.minecraftforge.registries.GameData$BlockCallbacks.onBake(GameData.java:518) ~[forge-1.18.2-40.1.51-universal.jar%23133!/:?] {re:classloading}
	at net.minecraftforge.registries.ForgeRegistry.bake(ForgeRegistry.java:591) ~[forge-1.18.2-40.1.51-universal.jar%23133!/:?] {re:classloading}
	at net.minecraftforge.registries.GameData.lambda$freezeData$9(GameData.java:297) ~[forge-1.18.2-40.1.51-universal.jar%23133!/:?] {re:mixin,re:classloading,pl:mixin:APP:kiwi.mixins.json:GameDataMixin,pl:mixin:A}
	at com.google.common.collect.HashBiMap.forEach(HashBiMap.java:572) ~[guava-31.0.1-jre.jar%2318!/:?] {}
	at net.minecraftforge.registries.GameData.freezeData(GameData.java:295) ~[forge-1.18.2-40.1.51-universal.jar%23133!/:?] {re:mixin,re:classloading,pl:mixin:APP:kiwi.mixins.json:GameDataMixin,pl:mixin:A}
	at net.minecraftforge.common.ForgeStatesProvider.lambda$new$5(ForgeStatesProvider.java:33) ~[forge-1.18.2-40.1.51-universal.jar%23133!/:?] {re:classloading}
	at net.minecraftforge.fml.ModLoader.lambda$dispatchAndHandleError$20(ModLoader.java:185) ~[fmlcore-1.18.2-40.1.51.jar%23129!/:?] {}
	at java.util.Optional.ifPresent(Optional.java:178) ~[?:?] {re:mixin}
	at net.minecraftforge.fml.ModLoader.dispatchAndHandleError(ModLoader.java:185) ~[fmlcore-1.18.2-40.1.51.jar%23129!/:?] {}
	at net.minecraftforge.fml.ModLoader.lambda$finishMods$17(ModLoader.java:175) ~[fmlcore-1.18.2-40.1.51.jar%23129!/:?] {}
	at java.lang.Iterable.forEach(Iterable.java:75) ~[?:?] {re:mixin}
	at net.minecraftforge.fml.ModLoader.finishMods(ModLoader.java:175) ~[fmlcore-1.18.2-40.1.51.jar%23129!/:?] {}
	at net.minecraftforge.client.loading.ClientModLoader.lambda$finishModLoading$6(ClientModLoader.java:126) ~[forge-1.18.2-40.1.51-universal.jar%23133!/:?] {re:classloading,pl:runtimedistcleaner:A}
	at net.minecraftforge.client.loading.ClientModLoader.lambda$createRunnableWithCatch$4(ClientModLoader.java:112) ~[forge-1.18.2-40.1.51-universal.jar%23133!/:?] {re:classloading,pl:runtimedistcleaner:A}
	at net.minecraftforge.client.loading.ClientModLoader.finishModLoading(ClientModLoader.java:126) ~[forge-1.18.2-40.1.51-universal.jar%23133!/:?] {re:classloading,pl:runtimedistcleaner:A}
	at net.minecraftforge.client.loading.ClientModLoader.lambda$onResourceReload$3(ClientModLoader.java:105) ~[forge-1.18.2-40.1.51-universal.jar%23133!/:?] {re:classloading,pl:runtimedistcleaner:A}
	at java.util.concurrent.CompletableFuture$UniRun.tryFire(CompletableFuture.java:787) ~[?:?] {}
	at java.util.concurrent.CompletableFuture$Completion.exec(CompletableFuture.java:483) ~[?:?] {}
	at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:373) ~[?:?] {}
	at java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1182) ~[?:?] {}
	at java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1655) ~[?:?] {}
	at java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1622) ~[?:?] {}
	at java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:165) ~[?:?] {}


A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Render thread
Stacktrace:
	at net.minecraft.client.renderer.GameRenderer.m_109093_(GameRenderer.java:882) ~[client-1.18.2-20220404.173914-srg.jar%23128!/:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:mixin:A,pl:runtimedistcleaner:A}
-- Overlay render details --
Details:
	Overlay name: net.minecraft.client.gui.screens.LoadingOverlay
Stacktrace:
	at net.minecraft.client.renderer.GameRenderer.m_109093_(GameRenderer.java:882) ~[client-1.18.2-20220404.173914-srg.jar%23128!/:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:mixin:A,pl:runtimedistcleaner:A}
	at net.minecraft.client.Minecraft.m_91383_(Minecraft.java:1044) ~[client-1.18.2-20220404.173914-srg.jar%23128!/:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:mixin:APP:architectury.mixins.json:MixinMinecraft,pl:mixin:APP:ars_nouveau.mixins.json:light.ClientMixin,pl:mixin:APP:balm.mixins.json:MinecraftMixin,pl:mixin:APP:bookshelf.common.mixins.json:client.AccessorMinecraft,pl:mixin:APP:flywheel.mixins.json:PausedPartialTickAccessor,pl:mixin:APP:iceberg.mixins.json:MinecraftMixin,pl:mixin:APP:immersiveengineering.mixins.json:accessors.client.MinecraftAccess,pl:mixin:APP:apoli.mixins.json:MinecraftClientMixin,pl:mixin:APP:create.mixins.json:WindowResizeMixin,pl:mixin:APP:ars_nouveau.mixins.json:camera.MinecraftMixin,pl:mixin:A,pl:runtimedistcleaner:A}
	at net.minecraft.client.Minecraft.m_91374_(Minecraft.java:663) ~[client-1.18.2-20220404.173914-srg.jar%23128!/:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:mixin:APP:architectury.mixins.json:MixinMinecraft,pl:mixin:APP:ars_nouveau.mixins.json:light.ClientMixin,pl:mixin:APP:balm.mixins.json:MinecraftMixin,pl:mixin:APP:bookshelf.common.mixins.json:client.AccessorMinecraft,pl:mixin:APP:flywheel.mixins.json:PausedPartialTickAccessor,pl:mixin:APP:iceberg.mixins.json:MinecraftMixin,pl:mixin:APP:immersiveengineering.mixins.json:accessors.client.MinecraftAccess,pl:mixin:APP:apoli.mixins.json:MinecraftClientMixin,pl:mixin:APP:create.mixins.json:WindowResizeMixin,pl:mixin:APP:ars_nouveau.mixins.json:camera.MinecraftMixin,pl:mixin:A,pl:runtimedistcleaner:A}
	at net.minecraft.client.main.Main.main(Main.java:205) ~[client-1.18.2-20220404.173914-srg.jar%23128!/:?] {re:classloading,pl:runtimedistcleaner:A}
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?] {}
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77) ~[?:?] {}
	at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?] {}
	at java.lang.reflect.Method.invoke(Method.java:568) ~[?:?] {}
	at net.minecraftforge.fml.loading.targets.CommonClientLaunchHandler.lambda$launchService$0(CommonClientLaunchHandler.java:31) ~[fmlloader-1.18.2-40.1.51.jar%2350!/:?] {}
	at cpw.mods.modlauncher.LaunchServiceHandlerDecorator.launch(LaunchServiceHandlerDecorator.java:37) [modlauncher-9.1.3.jar%2339!/:?] {}
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:53) [modlauncher-9.1.3.jar%2339!/:?] {}
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:71) [modlauncher-9.1.3.jar%2339!/:?] {}
	at cpw.mods.modlauncher.Launcher.run(Launcher.java:106) [modlauncher-9.1.3.jar%2339!/:?] {}
	at cpw.mods.modlauncher.Launcher.main(Launcher.java:77) [modlauncher-9.1.3.jar%2339!/:?] {}
	at cpw.mods.modlauncher.BootstrapLaunchConsumer.accept(BootstrapLaunchConsumer.java:26) [modlauncher-9.1.3.jar%2339!/:?] {}
	at cpw.mods.modlauncher.BootstrapLaunchConsumer.accept(BootstrapLaunchConsumer.java:23) [modlauncher-9.1.3.jar%2339!/:?] {}
	at cpw.mods.bootstraplauncher.BootstrapLauncher.main(BootstrapLauncher.java:149) [bootstraplauncher-1.0.0.jar:?] {}
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?] {}
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77) ~[?:?] {}
	at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?] {}
	at java.lang.reflect.Method.invoke(Method.java:568) ~[?:?] {}
	at io.github.zekerzhayard.forgewrapper.installer.Main.main(Main.java:57) [ForgeWrapper-mmc3.jar:mmc3] {}
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?] {}
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77) ~[?:?] {}
	at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?] {}
	at java.lang.reflect.Method.invoke(Method.java:568) ~[?:?] {}
	at org.multimc.onesix.OneSixLauncher.launchWithMainClass(OneSixLauncher.java:210) [NewLaunch.jar:?] {}
	at org.multimc.onesix.OneSixLauncher.launch(OneSixLauncher.java:245) [NewLaunch.jar:?] {}
	at org.multimc.EntryPoint.listen(EntryPoint.java:143) [NewLaunch.jar:?] {}
	at org.multimc.EntryPoint.main(EntryPoint.java:34) [NewLaunch.jar:?] {}


-- Last reload --
Details:
	Reload number: 1
	Reload reason: initial
	Finished: No
	Packs: Default, Mod Resources, quark-emote-pack

-- System Details --
Details:
	Minecraft Version: 1.18.2
	Minecraft Version ID: 1.18.2
	Operating System: Windows 10 (amd64) version 10.0
	Java Version: 17.0.2, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode, sharing), Oracle Corporation
	Memory: 3904985088 bytes (3724 MiB) / 5821693952 bytes (5552 MiB) up to 12582912000 bytes (12000 MiB)
	CPUs: 12
	Processor Vendor: GenuineIntel
	Processor Name: Intel(R) Core(TM) i7-9750H CPU @ 2.60GHz
	Identifier: Intel64 Family 6 Model 158 Stepping 10
	Microarchitecture: Coffee Lake
	Frequency (GHz): 2.59
	Number of physical packages: 1
	Number of physical CPUs: 6
	Number of logical CPUs: 12
	Graphics card #0 name: NVIDIA GeForce GTX 1660 Ti
	Graphics card #0 vendor: NVIDIA (0x10de)
	Graphics card #0 VRAM (MB): 4095.00
	Graphics card #0 deviceId: 0x2191
	Graphics card #0 versionInfo: DriverVersion=30.0.15.1179
	Memory slot #0 capacity (MB): 8192.00
	Memory slot #0 clockSpeed (GHz): 2.67
	Memory slot #0 type: DDR4
	Memory slot #1 capacity (MB): 8192.00
	Memory slot #1 clockSpeed (GHz): 2.67
	Memory slot #1 type: DDR4
	Virtual memory max (MB): 37798.11
	Virtual memory used (MB): 18959.48
	Swap memory total (MB): 21504.00
	Swap memory used (MB): 1222.28
	JVM Flags: 3 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xms409m -Xmx12000m
	Launched Version: 1.18.2
	Backend library: LWJGL version 3.2.2 SNAPSHOT
	Backend API: NVIDIA GeForce GTX 1660 Ti/PCIe/SSE2 GL version 3.2.0 NVIDIA 511.79, NVIDIA Corporation
	Window size: 854x480
	GL Caps: Using framebuffer using OpenGL 3.2
	GL debug messages: 
	Using VBOs: Yes
	Is Modded: Definitely; Client brand changed to 'forge'
	Type: Client (map_client.txt)
	Graphics mode: fancy
	Resource Packs: vanilla, mod_resources
	Current Language: English (US)
	CPU: 12x Intel(R) Core(TM) i7-9750H CPU @ 2.60GHz
	ModLauncher: 9.1.3+9.1.3+main.9b69c82a
	ModLauncher launch target: forgeclient
	ModLauncher naming: srg
	ModLauncher services: 
		 mixin PLUGINSERVICE 
		 eventbus PLUGINSERVICE 
		 slf4jfixer PLUGINSERVICE 
		 object_holder_definalize PLUGINSERVICE 
		 runtime_enum_extender PLUGINSERVICE 
		 capability_token_subclass PLUGINSERVICE 
		 accesstransformer PLUGINSERVICE 
		 runtimedistcleaner PLUGINSERVICE 
		 mixin TRANSFORMATIONSERVICE 
		 fml TRANSFORMATIONSERVICE 
	FML Language Providers: 
		minecraft@1.0
		lowcodefml@null
		javafml@null
	Mod List: 
		hexerei-0.1.19.jar                                |Hexerei                       |hexerei                       |0.1.19              |DONE      |Manifest: NOSIGNATURE
		TreeChop-1.18.2-0.15.7.jar                        |HT's TreeChop                 |treechop                      |0.15.7              |DONE      |Manifest: NOSIGNATURE
		radium-0.7.10.jar                                 |Radium                        |radium                        |0.7.10              |DONE      |Manifest: NOSIGNATURE
		Kiwi-1.18.2-forge-6.1.2.jar                       |Kiwi                          |kiwi                          |6.1.2               |DONE      |Manifest: NOSIGNATURE
		doubledoors_1.18.2-3.3.jar                        |Double Doors                  |doubledoors                   |3.3                 |DONE      |Manifest: NOSIGNATURE
		humancompanions-1.18.2-1.4.6.jar                  |Human Companions              |humancompanions               |1.18.2-1.4.6        |DONE      |Manifest: NOSIGNATURE
		supermartijn642configlib-1.0.9-mc1.18.jar         |SuperMartijn642's Config Lib  |supermartijn642configlib      |1.0.9               |DONE      |Manifest: NOSIGNATURE
		rechiseled-1.0.10-mc1.18.jar                      |rechiseled                    |rechiseled                    |1.0.10              |DONE      |Manifest: NOSIGNATURE
		Origins-1.18.2-1.4.1.1-unified.jar                |Additional Entity Attributes  |additionalentityattributes    |1.18.2-1.4.1.1      |DONE      |Manifest: NOSIGNATURE
		ConfigMenusForge-v3.2.0-1.18.2-Forge.jar          |Config Menus for Forge        |configmenusforge              |3.2.0               |DONE      |Manifest: 9a:09:85:98:65:c4:8c:11:c5:49:f6:d6:33:23:39:df:8d:b4:ff:92:84:b8:bd:a5:83:9f:ac:7f:2a:d1:4b:6a
		redstonepen-1.18.2-1.0.10-b1.jar                  |Redstone Pen                  |redstonepen                   |1.0.10-b1           |DONE      |Manifest: bf:30:76:97:e4:58:41:61:2a:f4:30:d3:8f:4c:e3:71:1d:14:c4:a1:4e:85:36:e3:1d:aa:2f:cb:22:b0:04:9b
		RemoveMouseoverHighlight-1.0.jar                  |Remove Mouseover Highlight    |rmh                           |1.0                 |DONE      |Manifest: NOSIGNATURE
		jei-1.18.2-9.5.5.174.jar                          |Just Enough Items             |jei                           |9.5.5.174           |DONE      |Manifest: NOSIGNATURE
		AdditionalBanners-Forge-1.18.2-7.0.4.jar          |AdditionalBanners             |additionalbanners             |7.0.4               |DONE      |Manifest: eb:c4:b1:67:8b:f9:0c:db:dc:4f:01:b1:8e:61:64:39:4c:10:85:0b:a6:c4:c7:48:f0:fa:95:f2:cb:08:3a:e5
		The_Graveyard_1.9_(FORGE)_for_1.18.2.jar          |The Graveyard                 |graveyard                     |1.9                 |DONE      |Manifest: NOSIGNATURE
		mcw-windows-2.0.3-mc1.18.2.jar                    |Macaw's Windows               |mcwwindows                    |2.0.3               |DONE      |Manifest: NOSIGNATURE
		dynamiclights-1.18.6.jar                          |Dynamic Lights                |dynamiclights                 |1.18.6              |DONE      |Manifest: NOSIGNATURE
		caelus-forge-1.18.1-3.0.0.2.jar                   |Caelus API                    |caelus                        |1.18.1-3.0.0.2      |DONE      |Manifest: NOSIGNATURE
		waystones-forge-1.18.2-10.0.0.jar                 |Waystones                     |waystones                     |10.0.0              |DONE      |Manifest: NOSIGNATURE
		mcw-paintings-1.0.3-mc1.18.2.jar                  |Macaw's Paintings             |mcwpaintings                  |1.0.3               |DONE      |Manifest: NOSIGNATURE
		journeymap-1.18.2-5.8.0.jar                       |Journeymap                    |journeymap                    |5.8.0               |DONE      |Manifest: NOSIGNATURE
		Placebo-1.18.2-6.4.0.jar                          |Placebo                       |placebo                       |6.4.0               |DONE      |Manifest: NOSIGNATURE
		citadel-1.11.3-1.18.2.jar                         |Citadel                       |citadel                       |1.11.3              |DONE      |Manifest: NOSIGNATURE
		alexsmobs-1.18.5.jar                              |Alex's Mobs                   |alexsmobs                     |1.18.5              |DONE      |Manifest: NOSIGNATURE
		TravelersBackpack-1.18.2-7.1.1.jar                |Traveler's Backpack           |travelersbackpack             |7.1.1               |DONE      |Manifest: NOSIGNATURE
		DungeonCrawl-1.18.2-2.3.7.jar                     |Dungeon Crawl                 |dungeoncrawl                  |2.3.7               |DONE      |Manifest: NOSIGNATURE
		Bookshelf-Forge-1.18.2-13.2.20.jar                |Bookshelf                     |bookshelf                     |13.2.20             |DONE      |Manifest: eb:c4:b1:67:8b:f9:0c:db:dc:4f:01:b1:8e:61:64:39:4c:10:85:0b:a6:c4:c7:48:f0:fa:95:f2:cb:08:3a:e5
		Apotheosis-1.18.2-5.3.5.jar                       |Apotheosis                    |apotheosis                    |5.3.5               |DONE      |Manifest: NOSIGNATURE
		mcw-doors-1.0.6-mc1.18.2.jar                      |Macaw's Doors                 |mcwdoors                      |1.0.6               |DONE      |Manifest: NOSIGNATURE
		balm-3.0.2+0.jar                                  |Balm                          |balm                          |3.0.2+0             |DONE      |Manifest: NOSIGNATURE
		cloth-config-6.2.62-forge.jar                     |Cloth Config v4 API           |cloth_config                  |6.2.62              |DONE      |Manifest: NOSIGNATURE
		forge-1.18.2-40.1.51-universal.jar                |Forge                         |forge                         |40.1.51             |DONE      |Manifest: 84:ce:76:e8:45:35:e4:0e:63:86:df:47:59:80:0f:67:6c:c1:5f:6e:5f:4d:b3:54:47:1a:9f:7f:ed:5e:f2:90
		twilightforest-1.18.2-4.1.1102-universal.jar      |The Twilight Forest           |twilightforest                |4.1.1102            |DONE      |Manifest: NOSIGNATURE
		infernalmobs-1.18.5.jar                           |Infernal Mobs                 |infernalmobs                  |1.18.5              |DONE      |Manifest: NOSIGNATURE
		DungeonsArise-1.18.2-2.1.50d-beta.jar             |When Dungeons Arise           |dungeons_arise                |2.1.50d-1.18.2      |DONE      |Manifest: NOSIGNATURE
		client-1.18.2-20220404.173914-srg.jar             |Minecraft                     |minecraft                     |1.18.2              |DONE      |Manifest: a1:d4:5e:04:4f:d3:d6:e0:7b:37:97:cf:77:b0:de:ad:4a:47:ce:8c:96:49:5f:0a:cf:8c:ae:b2:6d:4b:8a:3f
		TConstruct-1.18.2-3.5.0.17.jar                    |Tinkers' Construct            |tconstruct                    |3.5.0.17            |DONE      |Manifest: NOSIGNATURE
		Companion-1.18.2-forge-2.1.0.jar                  |Companion                     |companion                     |2.1.0               |DONE      |Manifest: NOSIGNATURE
		MagnumTorch-v3.1.3-1.18.2-Forge.jar               |Magnum Torch                  |magnumtorch                   |3.1.3               |DONE      |Manifest: 9a:09:85:98:65:c4:8c:11:c5:49:f6:d6:33:23:39:df:8d:b4:ff:92:84:b8:bd:a5:83:9f:ac:7f:2a:d1:4b:6a
		ImmersiveEngineering-1.18.2-8.0.0-146.jar         |Immersive Engineering         |immersiveengineering          |1.18.2-8.0.0-146    |DONE      |Manifest: 44:39:94:cf:1d:8c:be:3c:7f:a9:ee:f4:1e:63:a5:ac:61:f9:c2:87:d5:5b:d9:d6:8c:b5:3e:96:5d:8e:3f:b7
		silent-lib-1.18.2-6.2.0.jar                       |Silent Lib                    |silentlib                     |6.2.0               |DONE      |Manifest: NOSIGNATURE
		Jade-1.18.2-forge-5.2.1.jar                       |Jade                          |jade                          |5.2.1               |DONE      |Manifest: NOSIGNATURE
		mcw-fences-1.0.5-mc1.18.2.jar                     |Macaw's Fences and Walls      |mcwfences                     |1.0.5               |DONE      |Manifest: NOSIGNATURE
		supermartijn642corelib-1.0.16b-mc1.18.jar         |SuperMartijn642's Core Lib    |supermartijn642corelib        |1.0.16b             |DONE      |Manifest: NOSIGNATURE
		domum_ornamentum-1.18.2-1.0.50-ALPHA-universal.jar|Domum Ornamentum              |domum_ornamentum              |1.18.2-1.0.50-ALPHA |DONE      |Manifest: NOSIGNATURE
		Highlighter-1.18.1-1.1.2.jar                      |Highlighter                   |highlighter                   |1.1.2               |DONE      |Manifest: NOSIGNATURE
		Iceberg-1.18.2-1.0.44.jar                         |Iceberg                       |iceberg                       |1.0.44              |DONE      |Manifest: NOSIGNATURE
		flywheel-forge-1.18-0.6.2.jar                     |Flywheel                      |flywheel                      |1.18-0.6.2          |DONE      |Manifest: NOSIGNATURE
		create-mc1.18.2_v0.4.1.jar                        |Create                        |create                        |0.4.1               |DONE      |Manifest: NOSIGNATURE
		curios-forge-1.18.2-5.0.7.0.jar                   |Curios API                    |curios                        |1.18.2-5.0.7.0      |DONE      |Manifest: NOSIGNATURE
		Patchouli-1.18.2-69.jar                           |Patchouli                     |patchouli                     |0.0NONE             |DONE      |Manifest: NOSIGNATURE
		Mantle-1.18.2-1.9.26.jar                          |Mantle                        |mantle                        |1.9.26              |DONE      |Manifest: NOSIGNATURE
		blockui-1.18.2-0.0.48-ALPHA.jar                   |UI Library Mod                |blockui                       |1.18.2-0.0.48-ALPHA |DONE      |Manifest: NOSIGNATURE
		collective-1.18.2-4.28.jar                        |Collective                    |collective                    |4.28                |DONE      |Manifest: NOSIGNATURE
		arsomega-2.6.1.jar                                |Ars Omega                     |arsomega                      |1.18.2-2.2.1        |DONE      |Manifest: NOSIGNATURE
		AutoRegLib-1.7-52.jar                             |AutoRegLib                    |autoreglib                    |1.7-52              |DONE      |Manifest: NOSIGNATURE
		Quark-3.2-357.jar                                 |Quark                         |quark                         |3.2-357             |DONE      |Manifest: NOSIGNATURE
		FramedBlocks-5.0.1.jar                            |FramedBlocks                  |framedblocks                  |5.0.1               |DONE      |Manifest: NOSIGNATURE
		sprout-1.3.1-forge.jar                            |Sprout                        |sprout                        |1.3.1               |DONE      |Manifest: NOSIGNATURE
		structurize-1.18.2-1.0.411-ALPHA.jar              |Structurize                   |structurize                   |1.18.2-1.0.411-ALPHA|DONE      |Manifest: NOSIGNATURE
		multi-piston-1.18.2-1.2.7-ALPHA.jar               |Multi-Piston                  |multipiston                   |1.18.2-1.2.7-ALPHA  |DONE      |Manifest: NOSIGNATURE
		buildersaddition-1.18.2-20220308a.jar             |Builders Crafts & Addition    |buildersaddition              |1.18.2-20220308a    |DONE      |Manifest: NOSIGNATURE
		worldeditcuife3-forge-1.18.1-3.1.0.jar            |WorldEdit CUI 3 Forge Edition |worldeditcuife3               |3.1.0               |DONE      |Manifest: NOSIGNATURE
		worldedit-mod-7.2.10.jar                          |WorldEdit                     |worldedit                     |7.2.10+1742f98      |DONE      |Manifest: NOSIGNATURE
		minecolonies-1.18.2-1.0.803-BETA.jar              |MineColonies                  |minecolonies                  |1.18.2-1.0.803-BETA |DONE      |Manifest: NOSIGNATURE
		architectury-4.1.39.jar                           |Architectury                  |architectury                  |4.1.39              |DONE      |Manifest: NOSIGNATURE
		engineersdecor-1.18.2-1.1.22-b1.jar               |Engineer's Decor              |engineersdecor                |1.1.22-b1           |DONE      |Manifest: bf:30:76:97:e4:58:41:61:2a:f4:30:d3:8f:4c:e3:71:1d:14:c4:a1:4e:85:36:e3:1d:aa:2f:cb:22:b0:04:9b
		light-overlay-6.0.5-forge.jar                     |Light Overlay                 |lightoverlay                  |6.0.5               |DONE      |Manifest: NOSIGNATURE
		PuzzlesLib-v3.3.5-1.18.2-Forge.jar                |Puzzles Lib                   |puzzleslib                    |3.3.5               |DONE      |Manifest: 9a:09:85:98:65:c4:8c:11:c5:49:f6:d6:33:23:39:df:8d:b4:ff:92:84:b8:bd:a5:83:9f:ac:7f:2a:d1:4b:6a
		valhelsia_core-1.18.2-0.3.1.jar                   |Valhelsia Core                |valhelsia_core                |1.18.2-0.3.1        |DONE      |Manifest: NOSIGNATURE
		forbidden_arcanus-1.18.2-2.1.0-beta2.jar          |Forbidden & Arcanus           |forbidden_arcanus             |1.18.2-2.1.0-beta2  |DONE      |Manifest: NOSIGNATURE
		ChiselsBits-forge-1.18.2-1.2.83-universal.jar     |Chisels & bits                |chiselsandbits                |1.2.83              |DONE      |Manifest: NOSIGNATURE
		geckolib-forge-1.18-3.0.24.jar                    |GeckoLib                      |geckolib3                     |3.0.24              |DONE      |Manifest: NOSIGNATURE
		ars_nouveau-1.18.2-2.5.0.jar                      |Ars Nouveau                   |ars_nouveau                   |2.5.0               |DONE      |Manifest: NOSIGNATURE
		BetterModsButton-v3.2.2-1.18.2-Forge.jar          |Better Mods Button            |bettermodsbutton              |3.2.2               |DONE      |Manifest: 9a:09:85:98:65:c4:8c:11:c5:49:f6:d6:33:23:39:df:8d:b4:ff:92:84:b8:bd:a5:83:9f:ac:7f:2a:d1:4b:6a
		treasure-bags-1.18.2-1.7.0.jar                    |Treasure Bags                 |treasurebags                  |1.7.0               |DONE      |Manifest: NOSIGNATURE
	Crash Report UUID: cd8ede0a-c1cc-461a-ac1a-de7986bcf771
	Flywheel Backend: GL33 Instanced Arrays
	FML: 40.1
	Forge: net.minecraftforge:40.1.51
	FramedBlocks BlockEntity Warning: Not applicable
	Kiwi Modules: 
		kiwi:contributors
		kiwi:data
```

**Comment by stfwi** [comment]
Hi Matt, thanks for the hint - Radium is innocent here, this was purely and utterly a mess-up of mine ;) - handled in issue #207 (fixed in mod version b2).
The latest pushed mod version is https://www.curseforge.com/minecraft/mc-mods/engineers-decor/files/3837935.
Cheers,-
