### ISSUE TITLE
server crash on new version 1.12.2-1.0.20

### ISSUE THREAD

**Issue by Rutes** [stfwi/engineers-decor#96]
Hey there - love the mod. I was excited to see an update so I installed immediately :D 

Got a crash on my server. Seems to point to this mod, but not entirely sure: 

`java.lang.NoClassDefFoundError: wile/engineersdecor/blocks/BlockDecorLabeledCrate$BGui
    at java.lang.Class.getDeclaringClass0(Native Method)
    at java.lang.Class.getDeclaringClass(Class.java:1235)
    at java.lang.Class.getEnclosingClass(Class.java:1277)
    at java.lang.Class.getSimpleBinaryName(Class.java:1443)
    at java.lang.Class.getSimpleName(Class.java:1309)
    at org.spongepowered.mod.util.StaticMixinForgeHelper.getModIdFromClass(StaticMixinForgeHelper.java:323)
    at org.spongepowered.common.SpongeImplHooks.getModIdFromClass(SpongeImplHooks.java:1994)
    at org.spongepowered.common.registry.type.block.TileEntityTypeRegistryModule.doTileEntityRegistration(TileEntityTypeRegistryModule.java:156)
    at net.minecraft.tileentity.TileEntity.handler$zkl000$impl$registerTileEntityClassWithSpongeRegistry(TileEntity.java:3695)
    at net.minecraft.tileentity.TileEntity.register(TileEntity.java:37)
    at net.minecraftforge.fml.common.registry.GameRegistry.registerTileEntity(GameRegistry.java:234)
    at net.minecraftforge.fml.common.registry.GameRegistry.registerTileEntity(GameRegistry.java:239)
    at wile.engineersdecor.ModContent.registerBlocks(ModContent.java:714)
    at wile.engineersdecor.ModEngineersDecor$RegistrationSubscriptions.registerBlocks(ModEngineersDecor.java:128)
    at net.minecraftforge.fml.common.eventhandler.ASMEventHandler_275_RegistrationSubscriptions_registerBlocks_Register.invoke(.dynamic)
    at net.minecraftforge.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:90)
    at net.minecraftforge.fml.common.eventhandler.EventBus$1.invoke(EventBus.java:144)
    at net.minecraftforge.fml.common.eventhandler.EventBus.forgeBridge$post(EventBus.java:756)
    at net.minecraftforge.fml.common.eventhandler.EventBus.post(EventBus.java:703)
    at net.minecraftforge.registries.GameData.fireRegistryEvents(GameData.java:845)
    at net.minecraftforge.fml.common.Loader.preinitializeMods(Loader.java:630)
    at net.minecraftforge.fml.server.FMLServerHandler.beginServerLoading(FMLServerHandler.java:99)
    at net.minecraftforge.fml.common.FMLCommonHandler.onServerStart(FMLCommonHandler.java:333)
    at net.minecraft.server.dedicated.DedicatedServer.init(DedicatedServer.java:125)
    at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:486)
    at java.lang.Thread.run(Thread.java:748)
Caused by: java.lang.ClassNotFoundException: wile.engineersdecor.blocks.BlockDecorLabeledCrate$BGui
    at net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLoader.java:191)
    at java.lang.ClassLoader.loadClass(ClassLoader.java:418)
    at java.lang.ClassLoader.loadClass(ClassLoader.java:351)
    ... 26 more
Caused by: net.minecraftforge.fml.common.asm.ASMTransformerWrapper$TransformerException: Exception in class transformer net.minecraftforge.fml.common.asm.transformers.SideTransformer@7a8136b3 from coremod FMLCorePlugin
    at net.minecraftforge.fml.common.asm.ASMTransformerWrapper$TransformerWrapper.transform(ASMTransformerWrapper.java:260)
    at net.minecraft.launchwrapper.LaunchClassLoader.runTransformers(LaunchClassLoader.java:279)
    at net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLoader.java:176)
    ... 28 more
Caused by: java.lang.RuntimeException: Attempted to load class wile/engineersdecor/blocks/BlockDecorLabeledCrate$BGui for invalid side SERVER
    at net.minecraftforge.fml.common.asm.transformers.SideTransformer.transform(SideTransformer.java:62)
    at net.minecraftforge.fml.common.asm.ASMTransformerWrapper$TransformerWrapper.transform(ASMTransformerWrapper.java:256)
    ... 30 more`

full crash report here if needed: 
https://pastebin.com/xgyjJXv0

**Comment by stfwi** [comment]
Hi, this is related to issue #91, the exception occurs during the SpongeForge class scan, we thought that we had found and fixed the issue (I thought I had a reference to the GUI part of the mod somewhere, which is not existing on the server). So it looks the corresponding Sponge issue has to be reopened, too.

https://github.com/SpongePowered/SpongeForge/issues/3122.

**Comment by stfwi** [comment]
[crash-report.zip](https://github.com/stfwi/engineers-decor/files/4604265/crash-report.zip)

**Comment by stfwi** [comment]
Related issue: https://github.com/SpongePowered/SpongeForge/issues/3155.

**Comment by stfwi** [comment]
Ok, the sponge guys did close the issue without actually taking care, so I marked ED incompatible with Sponge, as already quite a few other mods. I hoped that this could be circumvented, but unfortunately there does not seem to be a path to resolve this in a cooperative way.
